[package]
name = "wfobj-rs"
version = "0.1.0"
edition = "2021"
authors = ["Zatarita"]
description = "Specification compliant OBJ parser"
readme = "README.md"
repository = "https://github.com/Zatarita/wfobj-rs"
license = "GPL-3.0-only "
keywords = ["Model", "WaveFront", "OBJ"]

[dependencies]
